import { useRef, useState } from "react";
import { useLocation } from "react-router-dom";
import {
  Camera,
  Upload,
  MapPin,
  Zap,
  Download,
  CheckCircle,
} from "lucide-react";

import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";

export default function RoofDetection() {
  const location = useLocation();

  const [detectionStep, setDetectionStep] = useState<
    "select" | "capture" | "processing" | "results"
  >("select");

  const [detectionMethod, setDetectionMethod] = useState<
    "camera" | "satellite" | "upload"
  >(
    location.state?.method === "satellite"
      ? "satellite"
      : "camera",
  );

  const [analysisProgress, setAnalysisProgress] = useState(0);

  const [uploadedImage, setUploadedImage] = useState<string | null>(
    null,
  );

  const [address, setAddress] = useState(
    location.state?.address || "",
  );

  const fileInputRef = useRef<HTMLInputElement>(null);

  /* POC calculation values */
  const roofArea = 245.8;

  const annualRainfall = 850;

  const runoffCoefficient = 0.8;

  const harvestEfficiency = 0.78;

  const harvestPotential = Math.round(
    roofArea *
      annualRainfall *
      runoffCoefficient *
      harvestEfficiency,
  );

  const estimatedCost = Math.round(
    roofArea * 175,
  );

  const annualSavings = Math.round(
    harvestPotential * 0.14,
  );

  const roi = (
    estimatedCost / annualSavings
  ).toFixed(1);

  const handleStartAnalysis = () => {
    setDetectionStep("processing");
    setAnalysisProgress(0);

    const interval = setInterval(() => {
      setAnalysisProgress((prev) => {
        if (prev >= 100) {
          clearInterval(interval);
          setDetectionStep("results");
          return 100;
        }

        return prev + 10;
      });
    }, 400);
  };

  const handleFileUpload = (
    event: React.ChangeEvent<HTMLInputElement>,
  ) => {
    const file = event.target.files?.[0];

    if (!file) {
      return;
    }

    const imageUrl = URL.createObjectURL(file);

    setUploadedImage(imageUrl);

    handleStartAnalysis();
  };

  const downloadReport = () => {
    const report =
      "AI ROOF ANALYSIS REPORT\n\n" +
      "====================================\n\n" +
      `Detection Method: ${detectionMethod}\n` +
      `Location: ${address || "Not provided"}\n\n` +
      `Roof Area: ${roofArea} m²\n` +
      `Annual Rainfall: ${annualRainfall} mm/year\n` +
      `Harvest Potential: ${harvestPotential.toLocaleString()} L/year\n` +
      `Runoff Coefficient: ${runoffCoefficient}\n` +
      `Harvest Efficiency: ${harvestEfficiency * 100}%\n\n` +
      "Recommended Structure: Percolation Pit\n\n" +
      `Estimated Implementation Cost: Rs. ${estimatedCost.toLocaleString()}\n` +
      `Estimated Annual Savings: Rs. ${annualSavings.toLocaleString()}\n` +
      `Estimated ROI Period: ${roi} years\n\n` +
      "====================================\n\n" +
      "This analysis is a POC estimate generated by the\n" +
      "Rainwater Harvesting project.\n";

    const blob = new Blob([report], {
      type: "text/plain",
    });

    const url = URL.createObjectURL(blob);

    const link = document.createElement("a");

    link.href = url;

    link.download =
      "AI-roof-analysis-report.txt";

    document.body.appendChild(link);

    link.click();

    document.body.removeChild(link);

    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-cyan-50 p-4">

      <div className="mx-auto max-w-4xl">

        {/* HEADER */}
        <div className="mb-8 text-center">

          <h1 className="text-3xl font-bold text-gray-900">
            AI Roof Detection
          </h1>

          <p className="mt-2 text-gray-600">
            Analyze your roof and get a personalized rainwater
            harvesting recommendation
          </p>

        </div>

        {/* PROGRESS */}
        <div className="mb-8">

          <div className="hidden items-center justify-center md:flex">

            {[
              "Select Method",
              "Capture / Upload",
              "AI Analysis",
              "Results",
            ].map((step, index) => {

              const currentIndex = [
                "select",
                "capture",
                "processing",
                "results",
              ].indexOf(detectionStep);

              return (
                <div
                  key={step}
                  className="flex items-center"
                >

                  <div
                    className={`flex h-8 w-8 items-center justify-center rounded-full text-sm font-medium ${
                      index <= currentIndex
                        ? "bg-blue-600 text-white"
                        : "bg-gray-200 text-gray-600"
                    }`}
                  >
                    {index + 1}
                  </div>

                  <span className="ml-2 text-sm font-medium text-gray-600">
                    {step}
                  </span>

                  {index < 3 && (
                    <div className="mx-4 h-0.5 w-8 bg-gray-200" />
                  )}

                </div>
              );
            })}

          </div>

        </div>

        {/* STEP 1 */}
        {detectionStep === "select" && (
          <Card className="border-0 shadow-lg">

            <CardHeader>
              <CardTitle>
                Choose Detection Method
              </CardTitle>
            </CardHeader>

            <CardContent>

              <div className="grid grid-cols-1 gap-4 md:grid-cols-3">

                {/* CAMERA */}
                <button
                  onClick={() =>
                    setDetectionMethod("camera")
                  }
                  className={`rounded-lg border-2 p-6 text-center ${
                    detectionMethod === "camera"
                      ? "border-blue-500 bg-blue-50"
                      : "border-gray-200"
                  }`}
                >
                  <Camera className="mx-auto h-12 w-12 text-blue-600" />

                  <h3 className="mt-3 font-semibold">
                    Live Camera
                  </h3>

                  <p className="mt-1 text-sm text-gray-600">
                    Capture a roof image
                  </p>
                </button>

                {/* SATELLITE */}
                <button
                  onClick={() =>
                    setDetectionMethod("satellite")
                  }
                  className={`rounded-lg border-2 p-6 text-center ${
                    detectionMethod === "satellite"
                      ? "border-blue-500 bg-blue-50"
                      : "border-gray-200"
                  }`}
                >
                  <MapPin className="mx-auto h-12 w-12 text-green-600" />

                  <h3 className="mt-3 font-semibold">
                    Satellite Imagery
                  </h3>

                  <p className="mt-1 text-sm text-gray-600">
                    Analyze by address
                  </p>
                </button>

                {/* UPLOAD */}
                <button
                  onClick={() =>
                    setDetectionMethod("upload")
                  }
                  className={`rounded-lg border-2 p-6 text-center ${
                    detectionMethod === "upload"
                      ? "border-blue-500 bg-blue-50"
                      : "border-gray-200"
                  }`}
                >
                  <Upload className="mx-auto h-12 w-12 text-purple-600" />

                  <h3 className="mt-3 font-semibold">
                    Upload Image
                  </h3>

                  <p className="mt-1 text-sm text-gray-600">
                    Upload a roof image
                  </p>
                </button>

              </div>

              <div className="mt-6 text-center">

                <Button
                  onClick={() =>
                    setDetectionStep("capture")
                  }
                  className="bg-blue-600 hover:bg-blue-700"
                >
                  Continue with{" "}
                  {detectionMethod === "camera"
                    ? "Camera"
                    : detectionMethod === "satellite"
                      ? "Satellite"
                      : "Upload"}
                </Button>

              </div>

            </CardContent>
          </Card>
        )}

        {/* STEP 2 */}
        {detectionStep === "capture" && (
          <Card className="border-0 shadow-lg">

            <CardHeader>
              <CardTitle>

                {detectionMethod === "camera" &&
                  "Camera Capture"}

                {detectionMethod === "satellite" &&
                  "Satellite Analysis"}

                {detectionMethod === "upload" &&
                  "Upload Roof Image"}

              </CardTitle>
            </CardHeader>

            <CardContent>

              {/* CAMERA */}
              {detectionMethod === "camera" && (
                <div className="text-center">

                  <div className="mx-auto flex h-64 w-full max-w-md items-center justify-center rounded-lg border-2 border-dashed border-gray-300 bg-gray-50">

                    <div>

                      <Camera className="mx-auto h-16 w-16 text-gray-400" />

                      <p className="mt-2 text-gray-600">
                        Camera preview area
                      </p>

                    </div>

                  </div>

                  <div className="mt-6 space-x-4">

                    <Button
                      onClick={handleStartAnalysis}
                      className="bg-blue-600 hover:bg-blue-700"
                    >
                      <Camera className="mr-2 h-4 w-4" />
                      Capture Roof
                    </Button>

                    <Button
                      variant="outline"
                      onClick={() =>
                        setDetectionStep("select")
                      }
                    >
                      Back
                    </Button>

                  </div>

                </div>
              )}

              {/* SATELLITE */}
              {detectionMethod === "satellite" && (
                <div className="space-y-4">

                  <div>

                    <label className="block text-sm font-medium text-gray-700">
                      Enter Address
                    </label>

                    <input
                      type="text"
                      value={address}
                      onChange={(e) =>
                        setAddress(e.target.value)
                      }
                      placeholder="Enter your complete address..."
                      className="mt-1 block w-full rounded-md border border-gray-300 px-3 py-2"
                    />

                  </div>

                  <div className="text-center">

                    <Button
                      onClick={handleStartAnalysis}
                      className="bg-green-600 hover:bg-green-700"
                    >
                      <MapPin className="mr-2 h-4 w-4" />
                      Analyze from Satellite
                    </Button>

                    <Button
                      variant="outline"
                      className="ml-4"
                      onClick={() =>
                        setDetectionStep("select")
                      }
                    >
                      Back
                    </Button>

                  </div>

                </div>
              )}

              {/* UPLOAD */}
              {detectionMethod === "upload" && (
                <div className="text-center">

                  <input
                    ref={fileInputRef}
                    type="file"
                    accept="image/*"
                    className="hidden"
                    onChange={handleFileUpload}
                  />

                  {!uploadedImage ? (
                    <div
                      onClick={() =>
                        fileInputRef.current?.click()
                      }
                      className="mx-auto flex h-64 w-full max-w-md cursor-pointer items-center justify-center rounded-lg border-2 border-dashed border-gray-300 bg-gray-50 hover:border-blue-400"
                    >

                      <div>

                        <Upload className="mx-auto h-16 w-16 text-purple-500" />

                        <p className="mt-2 font-medium text-gray-700">
                          Click to upload roof image
                        </p>

                        <p className="text-sm text-gray-500">
                          PNG, JPG up to 10MB
                        </p>

                      </div>

                    </div>
                  ) : (
                    <div className="mx-auto max-w-md">

                      <img
                        src={uploadedImage}
                        alt="Uploaded roof"
                        className="max-h-80 w-full rounded-lg border object-contain"
                      />

                      <p className="mt-3 text-sm text-green-600">
                        Image uploaded successfully
                      </p>

                    </div>
                  )}

                  <div className="mt-6">

                    <Button
                      variant="outline"
                      onClick={() =>
                        setDetectionStep("select")
                      }
                    >
                      Back
                    </Button>

                  </div>

                </div>
              )}

            </CardContent>
          </Card>
        )}

        {/* PROCESSING */}
        {detectionStep === "processing" && (
          <Card className="border-0 shadow-lg">

            <CardHeader>

              <CardTitle className="flex items-center">
                <Zap className="mr-2 h-6 w-6 text-yellow-500" />
                AI Analysis in Progress
              </CardTitle>

            </CardHeader>

            <CardContent>

              <div className="text-center">

                <div className="mx-auto h-32 w-32 animate-spin rounded-full border-4 border-blue-200 border-t-blue-600" />

                <h3 className="mt-6 text-lg font-semibold">
                  Analyzing Your Roof
                </h3>

                <p className="mt-2 text-gray-600">
                  Processing roof dimensions and rainwater
                  harvesting potential...
                </p>

                <div className="mt-6">

                  <Progress
                    value={analysisProgress}
                    className="mx-auto w-full max-w-md"
                  />

                  <p className="mt-2 text-sm text-gray-500">
                    {analysisProgress}% Complete
                  </p>

                </div>

                <div className="mx-auto mt-6 max-w-md space-y-2 text-left">

                  <div className="flex items-center text-sm">
                    <CheckCircle className="mr-2 h-4 w-4 text-green-500" />
                    Roof detection
                  </div>

                  <div className="flex items-center text-sm">
                    <CheckCircle className="mr-2 h-4 w-4 text-green-500" />
                    Area calculation
                  </div>

                  <div className="flex items-center text-sm">
                    <CheckCircle className="mr-2 h-4 w-4 text-green-500" />
                    Rainfall analysis
                  </div>

                  <div className="flex items-center text-sm">
                    <CheckCircle className="mr-2 h-4 w-4 text-green-500" />
                    Recommendation generation
                  </div>

                </div>

              </div>

            </CardContent>
          </Card>
        )}

        {/* RESULTS */}
        {detectionStep === "results" && (
          <div className="space-y-6">

            <Card className="border-0 shadow-lg">

              <CardHeader>

                <CardTitle className="flex items-center text-green-600">
                  <CheckCircle className="mr-2 h-6 w-6" />
                  Analysis Complete
                </CardTitle>

              </CardHeader>

              <CardContent>

                {/* UPLOADED IMAGE */}
                {uploadedImage && (
                  <div className="mb-6">

                    <h3 className="mb-3 font-semibold">
                      Analyzed Roof Image
                    </h3>

                    <img
                      src={uploadedImage}
                      alt="Analyzed roof"
                      className="mx-auto max-h-80 rounded-lg border object-contain"
                    />

                  </div>
                )}

                {/* RESULTS */}
                <div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">

                  <div className="rounded-lg bg-blue-50 p-4">

                    <h3 className="font-semibold text-blue-800">
                      Roof Area
                    </h3>

                    <p className="text-2xl font-bold text-blue-900">
                      {roofArea} m²
                    </p>

                    <Badge className="mt-1 bg-blue-100 text-blue-800">
                      94% POC Confidence
                    </Badge>

                  </div>

                  <div className="rounded-lg bg-cyan-50 p-4">

                    <h3 className="font-semibold text-cyan-800">
                      Harvest Potential
                    </h3>

                    <p className="text-2xl font-bold text-cyan-900">
                      {harvestPotential.toLocaleString()} L/year
                    </p>

                    <p className="text-sm text-cyan-700">
                      Based on regional rainfall
                    </p>

                  </div>

                  <div className="rounded-lg bg-green-50 p-4">

                    <h3 className="font-semibold text-green-800">
                      Recommended Structure
                    </h3>

                    <p className="text-lg font-bold text-green-900">
                      Percolation Pit
                    </p>

                    <p className="text-sm text-green-700">
                      Suitable for moderate soil permeability
                    </p>

                  </div>

                  <div className="rounded-lg bg-purple-50 p-4">

                    <h3 className="font-semibold text-purple-800">
                      Implementation Cost
                    </h3>

                    <p className="text-2xl font-bold text-purple-900">
                      ₹{estimatedCost.toLocaleString()}
                    </p>

                    <p className="text-sm text-purple-700">
                      Estimated materials & labor
                    </p>

                  </div>

                  <div className="rounded-lg bg-orange-50 p-4">

                    <h3 className="font-semibold text-orange-800">
                      ROI Period
                    </h3>

                    <p className="text-2xl font-bold text-orange-900">
                      {roi} years
                    </p>

                    <p className="text-sm text-orange-700">
                      Estimated break-even timeline
                    </p>

                  </div>

                  <div className="rounded-lg bg-indigo-50 p-4">

                    <h3 className="font-semibold text-indigo-800">
                      Annual Savings
                    </h3>

                    <p className="text-2xl font-bold text-indigo-900">
                      ₹{annualSavings.toLocaleString()}
                    </p>

                    <p className="text-sm text-indigo-700">
                      Estimated water bill reduction
                    </p>

                  </div>

                </div>

              </CardContent>
            </Card>

            {/* RESULT ACTIONS */}
            <Card className="border-0 shadow-lg">

              <CardContent className="pt-6">

                <div className="flex flex-wrap justify-center gap-3">

                  {/* ACTUAL DOWNLOAD */}
                  <Button
                    onClick={downloadReport}
                    className="bg-green-600 hover:bg-green-700"
                  >
                    <Download className="mr-2 h-4 w-4" />
                    Download Report
                  </Button>

                  <Button
                    variant="outline"
                    onClick={() => {
                      const report =
                        "SUBSIDY ELIGIBILITY SUMMARY\n\n" +
                        "Status: Potentially Eligible\n" +
                        "Recommended Structure: Percolation Pit\n" +
                        `Estimated Cost: Rs. ${estimatedCost.toLocaleString()}\n` +
                        "Please submit required documents to the applicable authority.";

                      const blob = new Blob(
                        [report],
                        {
                          type: "text/plain",
                        },
                      );

                      const url =
                        URL.createObjectURL(blob);

                      const link =
                        document.createElement("a");

                      link.href = url;

                      link.download =
                        "subsidy-summary.txt";

                      document.body.appendChild(link);

                      link.click();

                      document.body.removeChild(link);

                      URL.revokeObjectURL(url);
                    }}
                  >
                    Apply for Subsidy
                  </Button>

                  <Button
                    variant="outline"
                    onClick={() => {
                      setDetectionStep("select");
                      setAnalysisProgress(0);
                      setUploadedImage(null);
                      setAddress("");
                    }}
                  >
                    Analyze Another Roof
                  </Button>

                </div>

              </CardContent>
            </Card>

            {/* PLAN PREVIEW */}
            <Card className="border-0 shadow-lg">

              <CardHeader>
                <CardTitle>
                  Harvesting Plan Preview
                </CardTitle>
              </CardHeader>

              <CardContent>

                <p className="mb-4 text-center text-gray-600">
                  Recommended rainwater harvesting configuration
                  based on the analysis.
                </p>

                <img
                  src="/preview.jpg"
                  alt="Rainwater harvesting plan"
                  className="mx-auto w-full rounded-lg border"
                />

              </CardContent>
            </Card>

          </div>
        )}

      </div>
    </div>
  );
}